### ISSUE TITLE
Configure options

### ISSUE THREAD

**Issue by mantox74** [GeorgianStan/swipe-event-listener#4]
Sorry but is not clear how to configure options.
Can you create a demo?
Tanx

**Comment by GeorgianStan** [comment]
Hi @mantox74.

When calling the `SwipeEventListener` function you can pass all the options from that table, the ones that are also visible in the `Options` interface.

I created a discussions page for this repository and attached an example there. Here is the [link](https://github.com/GeorgianStan/swipe-event-listener/discussions/6).
